#!/usr/bin/env python3
"""One-off migration of the Unicode-to-LaTeX data into `untechxt`.

Run it from the repository root:

    python3 tools/migrate_tables.py

It reads the earlier port's hand-maintained table,
`initial-rust-port/src/tables.rs`, and produces two files of this crate:

* the `ENTRIES` block of `src/builtin/default_table.rs`, between the marker
  lines `// BEGIN ENTRIES (generated by tools/migrate_tables.py)` and
  `// END ENTRIES` (everything else in that file, the module documentation
  above all, is written by hand and is left alone), and
* `tests/goldens/latexencode/uni_chars_test_previous.txt`, a copy of the old
  conformance golden with the same command rename applied.

Two transformations happen on the way:

* **The mode column.** The old table stored mathematical spellings wrapped in
  `\\ensuremath{...}`. The new table stores the bare spelling plus a
  `ValueMode`, and the encoder's protection strategy adds the wrapper when the
  output is text. A value of the form `\\ensuremath{X}` whose opening brace
  closes at the very end becomes `X` with `MATH`; a value with no backslash at
  all becomes `ANY`; everything else stays as it is with `TEXT` -- including
  the three mixed values that hold an `\\ensuremath{...}` inside a text-mode
  spelling.
* **The command prefix.** Commands the builtin preamble snippets define used
  the `\\flm` prefix of the crate this data came from (FLM's
  `flm-latexencode`); they use `\\UnxT` here. The rest of each command name is
  unchanged.

Everything the migration relies on is asserted, so that a silent misreading of
the old file cannot slip through. After this script has run once,
`src/builtin/default_table.rs` is the hand-maintained source of truth; do not
run the script again over an edited table.

`tests/goldens/latexencode/README.md` is prose about this crate and is written
by hand, not by this script.

Python 3, standard library only.
"""

import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

OLD_TABLES = REPO / "initial-rust-port" / "src" / "tables.rs"
NEW_TABLE = REPO / "src" / "builtin" / "default_table.rs"
OLD_GOLDEN = (
    REPO / "initial-rust-port" / "tests" / "goldens" / "latexencode"
    / "uni_chars_test_previous.txt"
)
NEW_GOLDEN = (
    REPO / "tests" / "goldens" / "latexencode" / "uni_chars_test_previous.txt"
)

BEGIN_MARKER = "    // BEGIN ENTRIES (generated by tools/migrate_tables.py)"
END_MARKER = "    // END ENTRIES"

# One line of the old `DEFAULTS` table:
#     ('\u{00E9}', r#"\'e"#, BUILTINS), // LATIN SMALL LETTER E WITH ACUTE
OLD_ENTRY_RE = re.compile(
    r"^    \('\\u\{(?P<cp>[0-9A-Fa-f]+)\}', "
    r"r#\"(?P<value>.*)\"#, "
    r"(?P<profile>[A-Za-z_][A-Za-z_0-9]*)\), // (?P<name>.*)$"
)

ENSUREMATH = r"\ensuremath{"

# The rename: `\flm` followed by a letter, the rest of the name untouched.
FLM_RE = re.compile(r"\\flm(?=[A-Za-z])")

# What the plan says the migration must produce.
EXPECTED_TOTAL = 1549
EXPECTED_MODES = {"MATH": 935, "ANY": 34, "TEXT": 580}
EXPECTED_RENAMED = 68
EXPECTED_GOLDEN_RENAMED = 68
# The three values that mix a text-mode spelling with an inner `\ensuremath`.
EXPECTED_MIXED = {
    "038F": r"\'{}\ensuremath{\Omega}",
    "2109": r"\ensuremath{^\circ}F",
    "25AA": r"{\small\ensuremath{\blacksquare}}",
}


def fail(message):
    raise SystemExit("migrate_tables.py: " + message)


def rename_commands(text):
    """`\\flmScr` -> `\\UnxTScr`, and so on for every command of the snippets."""
    return FLM_RE.sub(r"\\UnxT", text)


def closing_brace(value, open_index):
    """Index of the `}` that closes the `{` at `open_index`, or None.

    `\\{` and `\\}` are escaped braces and do not count; a backslash always
    takes the next character with it.
    """
    if value[open_index] != "{":
        fail("closing_brace called at %r, which is not a brace" % value[open_index])
    depth = 0
    i = open_index
    while i < len(value):
        ch = value[i]
        if ch == "\\":
            i += 2
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def classify(value):
    """The `(mode, encoded)` pair of an old table value."""
    if value.startswith(ENSUREMATH):
        end = closing_brace(value, len(ENSUREMATH) - 1)
        if end == len(value) - 1:
            return "MATH", value[len(ENSUREMATH):-1]
    if "\\" not in value:
        return "ANY", value
    return "TEXT", value


def text_rendering(mode, encoded):
    """What the new entry writes in text mode -- the old value, unchanged."""
    if mode == "MATH":
        return ENSUREMATH + encoded + "}"
    return encoded


def read_old_entries(path):
    """The `(code point, value, profile, name)` rows of the old `DEFAULTS`."""
    text = path.read_text(encoding="utf-8")
    start = text.find("pub static DEFAULTS")
    if start < 0:
        fail("no `pub static DEFAULTS` in %s" % path)
    lines = text[start:].splitlines()
    if not lines[0].endswith("= &["):
        fail("unexpected first line of DEFAULTS: %r" % lines[0])
    rows = []
    for line in lines[1:]:
        if line.strip() == "];":
            break
        match = OLD_ENTRY_RE.match(line)
        if match is None:
            fail("cannot parse table line: %r" % line)
        rows.append(
            (
                match.group("cp"),
                match.group("value"),
                match.group("profile"),
                match.group("name"),
            )
        )
    else:
        fail("the DEFAULTS table is not terminated by `];`")
    return rows


def migrate_entries(rows):
    """The new entry lines, with every check the plan asks for."""
    if len(rows) != EXPECTED_TOTAL:
        fail("read %d entries, expected %d" % (len(rows), EXPECTED_TOTAL))

    modes = Counter()
    renamed = 0
    mixed = {}
    previous = -1
    lines = []

    for cp, old_value, profile, name in rows:
        code_point = int(cp, 16)
        if code_point <= previous:
            fail("code points are not strictly ascending at U+%s" % cp)
        previous = code_point

        value = rename_commands(old_value)
        if value != old_value:
            renamed += 1
        if "\\flm" in value:
            fail("a `\\flm` command survived the rename at U+%s: %r" % (cp, value))

        mode, encoded = classify(value)
        modes[mode] += 1
        if mode == "TEXT" and "\\ensuremath" in encoded:
            mixed[cp] = encoded

        # The new entry must render in text mode exactly as the old one did.
        if text_rendering(mode, encoded) != value:
            fail(
                "U+%s does not round-trip: %r as %s gives %r"
                % (cp, value, mode, text_rendering(mode, encoded))
            )

        if '"#' in encoded:
            fail("U+%s cannot be written as `r#\"...\"#`: %r" % (cp, encoded))

        lines.append(
            "    ('\\u{%s}', r#\"%s\"#, %s, %s), // %s"
            % (cp, encoded, mode, profile, name)
        )

    for mode, expected in EXPECTED_MODES.items():
        if modes[mode] != expected:
            fail("%d entries are %s, expected %d" % (modes[mode], mode, expected))
    if sum(modes.values()) != EXPECTED_TOTAL:
        fail("the modes do not add up to %d" % EXPECTED_TOTAL)
    if renamed != EXPECTED_RENAMED:
        fail(
            "%d entries changed under the `\\flm` -> `\\UnxT` rename, expected %d"
            % (renamed, EXPECTED_RENAMED)
        )
    if mixed != EXPECTED_MIXED:
        fail("the mixed text/math entries are %r, expected %r" % (mixed, EXPECTED_MIXED))

    return lines, modes, renamed


def write_entries_block(path, lines):
    """Replace the marked `ENTRIES` block of `path`, keeping the rest."""
    text = path.read_text(encoding="utf-8")
    old_lines = text.splitlines(keepends=True)
    begins = [i for i, l in enumerate(old_lines) if l.rstrip("\n") == BEGIN_MARKER]
    ends = [i for i, l in enumerate(old_lines) if l.rstrip("\n") == END_MARKER]
    if len(begins) != 1 or len(ends) != 1 or begins[0] >= ends[0]:
        fail(
            "%s must hold exactly one `%s` line followed by one `%s` line"
            % (path, BEGIN_MARKER.strip(), END_MARKER.strip())
        )
    body = [line + "\n" for line in lines]
    new_lines = old_lines[: begins[0] + 1] + body + old_lines[ends[0] :]
    path.write_text("".join(new_lines), encoding="utf-8")


def copy_golden(source, destination):
    """Copy the conformance golden, renaming the `\\flm` commands in it."""
    old = source.read_text(encoding="utf-8")
    new = rename_commands(old)
    if "\\flm" in new:
        fail("a `\\flm` command survived the rename in the golden")

    old_lines = old.splitlines(keepends=True)
    new_lines = new.splitlines(keepends=True)
    if len(old_lines) != len(new_lines):
        fail("the golden gained or lost lines under the rename")
    changed = sum(1 for a, b in zip(old_lines, new_lines) if a != b)
    if changed != EXPECTED_GOLDEN_RENAMED:
        fail(
            "%d golden lines changed under the rename, expected %d"
            % (changed, EXPECTED_GOLDEN_RENAMED)
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(new, encoding="utf-8")
    return changed


def main():
    for path in (OLD_TABLES, OLD_GOLDEN, NEW_TABLE):
        if not path.is_file():
            fail("%s does not exist (run this from the repository root)" % path)

    rows = read_old_entries(OLD_TABLES)
    lines, modes, renamed = migrate_entries(rows)
    write_entries_block(NEW_TABLE, lines)
    golden_changed = copy_golden(OLD_GOLDEN, NEW_GOLDEN)

    print("%s: %d entries" % (NEW_TABLE.relative_to(REPO), len(lines)))
    print(
        "  modes: %d MATH, %d TEXT, %d ANY"
        % (modes["MATH"], modes["TEXT"], modes["ANY"])
    )
    print("  `\\flm` -> `\\UnxT`: %d entries renamed" % renamed)
    print(
        "%s: %d lines renamed"
        % (NEW_GOLDEN.relative_to(REPO), golden_changed)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
